-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.33 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table noraruot_sistema_v2.asignatures: ~3 rows (approximately)
INSERT INTO `asignatures` (`id`, `name`, `description`, `code`, `year`, `prev_id`, `workload`, `credits`, `created_at`, `updated_at`) VALUES
	(1, 'Administración y Planificación Financiera', NULL, 'APF0', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 'Aplicación práctica de las Resoluciones emitidas por la SEPRELAD', NULL, 'APRS0', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 'Aplicación práctica de matriz de riesgos, de la debida diligencia y reporte de operaciones sospechosas.', NULL, 'APMR', NULL, NULL, NULL, 2, NULL, NULL),
	(4, 'Auditoría de Bancos y Financieras', NULL, 'ABF0', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 'Auditoría de Costos ', NULL, 'ACO002', '2017', NULL, 40, NULL, NULL, NULL),
	(6, 'Auditoría de Gestión', NULL, 'AGE001', '2017', NULL, 30, NULL, NULL, NULL),
	(7, 'Auditoría Financiera', NULL, 'AFI002', '2017', NULL, 40, NULL, NULL, NULL),
	(8, 'Auditoría Forense y Pericia Contable', NULL, 'AFP001', '2017', NULL, 30, NULL, NULL, NULL),
	(9, 'Auditoría Impositiva Avanzada', NULL, 'AIM03', '2022', 263, 50, 4, NULL, NULL),
	(10, 'Auditoría informática', NULL, 'AIN002', '2017', NULL, 30, NULL, NULL, NULL),
	(11, 'Auditoría Interna', NULL, 'AIN002', '2017', NULL, 40, NULL, NULL, NULL),
	(12, 'Auditoría Tributaria ', NULL, 'ATR0', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 'Auditoría y Fiscalización Tributaria', NULL, 'AFT001', '2017', NULL, 30, NULL, NULL, NULL),
	(14, 'Aula Invertida y Uso de las TIC’s', NULL, 'AIT0', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 'Casos conflictivos para la aplicación del Principio de Independencia en la exportación de soja. Ejercicios prácticos y otras cuestiones relacionadas directa o indirectamente con los precios de transferencia y sus medios probatorios.', NULL, 'EJP', NULL, NULL, NULL, NULL, NULL, NULL),
	(16, 'Constitución y funcionamiento de los demás tipos societarios en Paraguay', NULL, 'C0F0', NULL, NULL, NULL, NULL, NULL, NULL),
	(17, 'Contabilidad Agropecuaria ', NULL, 'COA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(18, 'Contabilidad Avanzada ', NULL, 'CAV0', NULL, NULL, NULL, NULL, NULL, NULL),
	(19, 'Contabilidad de Costos ', NULL, 'CCO0', NULL, NULL, NULL, NULL, NULL, NULL),
	(20, 'Contabilidad Financiera Avanzada', NULL, 'CFA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(21, 'Contabilidad Gubernamental ', NULL, 'COG0', NULL, NULL, NULL, NULL, NULL, NULL),
	(22, 'Contabilidad para Cooperativas', NULL, 'COC0', NULL, NULL, NULL, NULL, NULL, NULL),
	(23, 'Contrato con el Estado', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(24, 'Contratos Comerciales Típicos', NULL, 'CCT0', NULL, NULL, NULL, NULL, NULL, NULL),
	(25, 'Contratos de Propiedad Industrial e Intelectual ', NULL, 'CPI0', NULL, NULL, NULL, NULL, NULL, NULL),
	(26, 'Contratos de Trabajo', NULL, 'CDT0', NULL, NULL, NULL, NULL, NULL, NULL),
	(27, 'Contratos del Comercio Internacional', NULL, 'CCI0', NULL, NULL, NULL, NULL, NULL, NULL),
	(28, 'Coordinación Nacional ALA/CFT y Experiencia Nacional e Internacional (Enfoque Basado en Riesgo)', NULL, 'CNE00', NULL, NULL, NULL, NULL, NULL, NULL),
	(29, 'Cuestiones a tener en cuenta desde la óptica del control de la SET a los auditores, a las empresas obligadas a realizar el informe y a las que no lo hacen. Aspectos formales y Materiales. Jurisprudencia de otros países.', NULL, 'CAP', NULL, NULL, NULL, NULL, NULL, NULL),
	(30, 'Cuestiones contables aplicadas al IRE', NULL, 'IGE0', NULL, NULL, NULL, NULL, NULL, NULL),
	(31, 'Currículum de la Educación Superior', NULL, 'CES0', NULL, NULL, NULL, NULL, NULL, NULL),
	(32, 'De las figuras de reorganización empresarial y empresas vinculadas', NULL, 'FRE0', NULL, NULL, NULL, NULL, NULL, NULL),
	(33, 'Derecho Laboral vs Derecho Tributario', NULL, 'DLT0', NULL, NULL, NULL, NULL, NULL, NULL),
	(34, 'Derecho Laboral y su relación con el Derecho Tributario', NULL, 'DLT0', NULL, NULL, NULL, NULL, NULL, NULL),
	(35, 'Derecho Tributario Constitucional y Sustantivo', NULL, 'DTC01', '2022', 120, 40, 2.7, NULL, NULL),
	(36, 'Derechos Reales y Defensa de la Competencia Comercial', NULL, 'DRD0', NULL, NULL, NULL, NULL, NULL, NULL),
	(37, 'Diseño de Sistema de Información General', NULL, 'DSI0', NULL, NULL, NULL, NULL, NULL, NULL),
	(38, 'Diseño e innovación en la enseñanza', NULL, 'DIE0', NULL, NULL, NULL, NULL, NULL, NULL),
	(39, 'Diseño y Gestión de Proyectos Académicos', NULL, 'DPA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(40, 'Disposiciones de prevención de lavado de activo aplicables a las empresas en general.', NULL, 'DPL0', NULL, NULL, NULL, NULL, NULL, NULL),
	(41, 'Disposiciones de prevención de lavado de activos aplicables a las empresas en general', NULL, 'DPL0', NULL, NULL, NULL, NULL, NULL, NULL),
	(42, 'Estándares Nacionales e Internacionales de Cumplimiento ALA/CFT-FP', NULL, 'ENIALA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(43, 'Estrategias y técnicas Didácticas ', NULL, 'ETD0', NULL, NULL, NULL, NULL, NULL, NULL),
	(44, 'Evaluación del Proceso de Aprendizaje', NULL, 'EPA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(45, 'Figuras Empresariales para las Micro y Pequeña Empresa. EU. EIRL. EAS', NULL, 'FEM0', NULL, NULL, NULL, NULL, NULL, NULL),
	(46, 'Figuras Empresariales para las Micro y Pequeña Empresa. EU. EIRL. EAS. Reorganización empresarial y empresas vinculadas', NULL, 'FEM0', NULL, NULL, NULL, NULL, NULL, NULL),
	(47, 'Figuras empresariales para las Micro y Pequeñas empresas EU. EIRL EAS', NULL, 'FEM0', NULL, NULL, NULL, NULL, NULL, NULL),
	(48, 'Fiscalidad Internacional. Control de Precios de Transferencias', NULL, 'FIC0', NULL, NULL, NULL, NULL, NULL, NULL),
	(49, 'Formación práctica del auditor de Precios de Transferencia en Paraguay, a fin de emitir el Estudio Técnico requerido como garantía del cumplimiento del Principio de Plena Independencia.', NULL, 'FPAP', NULL, NULL, NULL, NULL, NULL, NULL),
	(50, 'Fuentes y Principios del Derecho Laboral', NULL, 'FDL0', NULL, NULL, NULL, NULL, NULL, NULL),
	(51, 'Gabinete Laboral', NULL, 'GLL0', NULL, NULL, NULL, NULL, NULL, NULL),
	(52, 'Gestión de las Sociedades Anónimas. Aspectos legales y conflictivos', NULL, 'GSA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(53, 'Gobierno Corporativo Empresarial. Principios para la Debida Diligencia', NULL, 'GCP0', NULL, NULL, NULL, NULL, NULL, NULL),
	(54, 'Grupos empresariales. Acuerdos de accionistas. Acciones de responsabilidad.', NULL, 'GAA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(55, 'Imposición a la Renta Empresarial y a los Dividendos y Utilidades. Compliance', NULL, 'REID', NULL, NULL, NULL, NULL, NULL, NULL),
	(56, 'Imposición a las Ganancias Empresariales. Parte General (IRE)', NULL, 'IGE01', '2022', 149, 40, 2.7, NULL, NULL),
	(57, 'Imposición a las Ganancias Empresariales. Parte Práctica (IRE)', NULL, 'IGE02', '2022', 149, 40, 2.7, NULL, NULL),
	(58, 'Imposición a los Dividendos y Utilidades. Transparencia del Beneficiario Final', NULL, 'IDU01', '2022', 254, 40, 2.7, NULL, NULL),
	(59, 'Imposición al Consumo. IVA - ISC', NULL, 'ICO02', '2022', 150, 60, 4, NULL, NULL),
	(60, 'Imposición sobre la Renta de las Personas Físicas', NULL, 'IRP01', '2022', 254, 40, 2.7, NULL, NULL),
	(61, 'Impuesto a la Renta Personal (IRP) y a los Dividendos (IDU)', NULL, 'IRPI0', NULL, NULL, NULL, NULL, NULL, NULL),
	(62, 'Introducción a las normas internacionales en materia de precios de transferencia y su regulación específica en el Paraguay.', NULL, 'IPT0', NULL, NULL, NULL, NULL, NULL, NULL),
	(63, 'Introducción al Derecho Societario Paraguayo en la Era de la Transparencia.', NULL, 'IDS0', NULL, NULL, NULL, NULL, NULL, NULL),
	(64, 'Introducción al estudio sobre Prevención Lavado de Activos/FT/FP', NULL, 'IPLA00', NULL, NULL, NULL, NULL, NULL, NULL),
	(65, 'Investigación Antilavado de Activos/CFT', NULL, 'INAL', NULL, NULL, NULL, NULL, NULL, NULL),
	(66, 'ISAE 3000 y otras Normas Complementarias  ', NULL, 'ISA01', '2022', 125, 30, 2, NULL, NULL),
	(67, 'Las NIIF para Pymes', NULL, 'NPY0', NULL, NULL, NULL, NULL, NULL, NULL),
	(68, 'Legislación Educativa', NULL, 'LGE0', NULL, NULL, NULL, NULL, NULL, NULL),
	(69, 'Marco Jurídico Nacional en Prevención de Lavado de Activos/FT/FP', NULL, 'MPLA00', NULL, NULL, NULL, NULL, NULL, NULL),
	(70, 'Mercado de Valores, Negocios Fiduciarios y Securitización ', NULL, 'MVN0', NULL, NULL, NULL, NULL, NULL, NULL),
	(71, 'Normas Especiales de Valoración de Operaciones', NULL, 'NVO01', '2022', 122, 40, 2.6667, NULL, NULL),
	(72, 'Normas Internacionales de Auditoría (NIA)', NULL, 'NIA02', '2022', 259, 60, 3.3, NULL, NULL),
	(73, 'Normas Internacionales de Contabilidad', NULL, 'NIC0', NULL, NULL, NULL, NULL, NULL, NULL),
	(74, 'Normas Internacionales de Información Financiera (NIIF). NIIF para Pymes', NULL, 'NIF03', '2022', 261, 60, 3.3, NULL, NULL),
	(75, 'Organismos Internacionales e Intergubernamentales en Prevención de Lavado de Activos/FT/FP', NULL, 'OPLA00', NULL, NULL, NULL, NULL, NULL, NULL),
	(76, 'Papeles de Trabajo y otras Cuestiones Prácticas', NULL, 'PAT001', '2017', NULL, 30, NULL, NULL, NULL),
	(77, 'Planificación Fiscal Internacional de Empresas aplicables en Paraguay', NULL, 'PFI0', NULL, NULL, NULL, NULL, NULL, NULL),
	(78, 'Planificación y Práctica Docente con uso de las TIC’s ', NULL, 'PPD0', NULL, NULL, NULL, NULL, NULL, NULL),
	(79, 'Práctica Profesional', NULL, 'PPL0', NULL, NULL, NULL, NULL, NULL, NULL),
	(80, 'Práctica Profesional en Auditoría Impositiva', NULL, 'PPA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(81, 'Principios aplicables al Derecho Contractual, Societario y Tributario', NULL, 'PAD0', NULL, NULL, NULL, NULL, NULL, NULL),
	(82, 'Procedimiento Laboral y Análisis de casos. Parte I', NULL, 'PLC0', NULL, NULL, NULL, NULL, NULL, NULL),
	(83, 'Procedimiento Laboral y Análisis de casos. Parte II ', NULL, 'PLC0', NULL, NULL, NULL, NULL, NULL, NULL),
	(84, 'Procedimiento Tributario y Defensa del Contribuyente', NULL, 'LVD001', '2017', NULL, 30, NULL, NULL, NULL),
	(85, 'Procesos de Investigación Científica ', NULL, 'PIC0', NULL, NULL, NULL, NULL, NULL, NULL),
	(86, 'Procesos de Reorganización Empresarial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(87, 'Programa de Cumplimiento de Antilavado de Activos/CFT-FP', NULL, 'PCLA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(88, 'Redacción práctica de Manuales de Prevención y Gestión de los Riesgos de LA/FT', NULL, 'RPM', NULL, NULL, NULL, NULL, NULL, NULL),
	(89, 'Régimen de Incentivos Fiscales y Asesoramiento', NULL, 'RIF0', NULL, NULL, NULL, NULL, NULL, NULL),
	(90, 'Régimen de Incentivos Fiscales y Asesoramiento al Inversionista', NULL, 'RIF0', NULL, NULL, NULL, NULL, NULL, NULL),
	(91, 'Régimen de Retenciones a Residentes y No Residentes Fiscales', NULL, 'INR01', '2022', 130, 40, 2.7, NULL, NULL),
	(92, 'Régimen de Seguro Social Obligatorio', NULL, 'SSO0', NULL, NULL, NULL, NULL, NULL, NULL),
	(93, 'Régimen Penal Tributario y normas de SEPRELAD', NULL, 'RPT01', '2022', 258, 40, 2, NULL, NULL),
	(94, 'Regímenes de Incentivos Fiscales y Asesoramiento al Inversionista', NULL, 'RIF0', NULL, NULL, NULL, NULL, NULL, NULL),
	(95, 'Registro de Beneficiario Fiscal y reglas del GAFFI', NULL, 'RBF0', NULL, NULL, NULL, NULL, NULL, NULL),
	(96, 'Reglamentaciones emitidas por la SEPRELAD', NULL, 'RSE00', NULL, NULL, NULL, NULL, NULL, NULL),
	(97, 'Regulación laboral de los funcionarios públicos', NULL, 'RFP0', NULL, NULL, NULL, NULL, NULL, NULL),
	(98, 'Resolución de conflictos laborales', NULL, 'RCL0', NULL, NULL, NULL, NULL, NULL, NULL),
	(99, 'Responsabilidad tributaria, civil y penal de los órganos empresariales, contador y asesores', NULL, 'RTC0', NULL, NULL, NULL, NULL, NULL, NULL),
	(100, 'Responsabilidad tributaria, civil y penal de los órganos empresariales, contadores y asesores', NULL, 'RTC0', NULL, NULL, NULL, NULL, NULL, NULL),
	(101, 'Riesgos y Métodos del Lavado de Activos y la financiación del Terrorismo', NULL, 'RMLA0', NULL, NULL, NULL, NULL, NULL, NULL),
	(102, 'Rol del Oficial de Cumplimiento en PLA/FT/FP (Complementario para Oficiales de Cumplimiento)', NULL, 'ROC00', NULL, NULL, NULL, NULL, NULL, NULL),
	(103, 'Sanciones y Cumplimiento de Leyes Laborales', NULL, 'SLL0', NULL, NULL, NULL, NULL, NULL, NULL),
	(104, 'Teorías y Modelos Pedagógicos', NULL, 'TMP0', NULL, NULL, NULL, NULL, NULL, NULL),
	(105, 'Tratamiento contable de las acciones y cuotas. Valuación Patrimonial', NULL, 'TVP0', NULL, NULL, NULL, NULL, NULL, NULL),
	(106, 'Tributación al Comercio Exterior', NULL, 'TCE002', '2017', NULL, 40, NULL, NULL, NULL),
	(107, 'Tributación de Cooperativas y Entidades sin Fines de Lucro', NULL, 'CCO0', NULL, NULL, NULL, NULL, NULL, NULL),
	(108, 'Contabilidad Sectorial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(109, 'Contratos bancarios y financieros. Primera parte', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(110, 'Contratos bancarios y financieros. Segunda parte', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(111, 'Contratos de Reorganizacion y Colaboracion Empresarial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(112, 'Contratos Societarios y Uniones Transitorias', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(113, 'De los contratos con el Estado', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(114, 'De los contratos en Particular. Segunda Parte', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(115, 'De los contratos en Particular. Tercera Parte', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(116, 'De los Impuestos Fiscales Internos. Primera parte', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(117, 'De los Impuestos Fiscales Internos. Segunda parte', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(118, 'Del comercio Internacional y sus contratos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(119, 'Derecho Constitucional Economico', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(120, 'Derecho Tributario Sustantivo y Asesoramiento Impositivo', NULL, 'ITD001', '2017', NULL, 30, NULL, NULL, NULL),
	(121, 'Derecho y contratos societarios', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(122, 'Impuestos a las Ganancias Agropecuarias', NULL, 'IGA002', '2017', NULL, 40, NULL, NULL, NULL),
	(123, 'Interpretacion de la Ley Tributaria. Derecho Tributario Sustantivo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(124, 'Mercado de Valores Negocios Fiduciarios y Securitizacion', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(125, 'Otras Auditorias Sectoriales', NULL, 'OAS001', '2017', NULL, 20, NULL, NULL, NULL),
	(126, 'Planeamiento Tributario', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(127, 'Practica Profesional en la Liquidacion de los Impuestos Fiscales Internos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(128, 'Practica Profesional para la realizacion de una Auditoria', NULL, 'PPA002', '2017', NULL, 30, NULL, NULL, NULL),
	(129, 'Principios Aplicables al Derecho Contractual Societario y Tributario', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(130, 'Retenciones Nacionales e Internacionales', NULL, 'RNI003', '2017', NULL, 50, NULL, NULL, NULL),
	(131, 'Tasas e Impuestos Municipales', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(132, 'Asesoramiento Impositivo para Accionistas y Obligaciones con las Reglas de la Nueva Reforma Tributaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(133, 'Auditoria de CERO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(134, 'Aula Invertida y Uso de las TICs', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(135, 'CIERRE FISCAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(136, 'CUADRO DE REVALUO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(137, 'Cerrando el IRP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(138, 'Cierre Fiscal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(139, 'Conceptos generales de la actividad agropecuaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(140, 'Contabilidad desde Cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(141, 'Convergencia y Cierre Fiscal de los EEFF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(142, 'Costo de Cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(143, 'DOCENTE Y PROFESIONAL TECNOLOGICO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(144, 'Disposiciones Generales', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(145, 'Empresas por Acciones Simplificadas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(146, 'FLUJO DE EFECTIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(147, 'GABINETE IMPUESTO A LAS GANANCIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(148, 'Gabinete Liquidacion de IRP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(149, 'Impuestos a las Ganancias Empresariales', NULL, 'IGE002', '2017', 0, 70, NULL, NULL, NULL),
	(150, 'IMPUESTO AL CONSUMO (IVA)', NULL, 'ICO002', '2017', NULL, 60, NULL, NULL, NULL),
	(151, 'IRE desde CERO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(152, 'IRP + IDU de Cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(153, 'IVA desde CERO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(154, 'Imposicion a los No Residentes (INR). Retenciones', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(155, 'Liquidando el IRP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(156, 'Negocios Fiduciarios y Fideicomiso', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(157, 'Normas APA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(158, 'PREVENCION DE LAVADO DE ACTIVOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(159, 'Principales modificaciones de la ley cooperativas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(160, 'Procesos de la Investigación Científica', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(161, 'Seminario Precios de Transferencia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(162, 'TRATAMIENTO TRIBUTARIO DE LA COOP Y ESFL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(163, 'Transparencia en el Regimen de Sociedades', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(164, 'Tributacion Intensiva para concurso de Escribanos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(165, '2202 maestria impuestos  y auditoria maia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(166, 'aplicacin prctica de la rg n 9021', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(167, 'asesoramiento tratamiento de acciones y obligaciones formales sa valuaciones patrimoniales', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(168, 'beneficiario final', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(169, 'beneficiario final asesoramiento impositivo para accionistas hasta el ejercicio 2019 ycon las reglas de la nueva reforma tributaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(170, 'cierre contable de actividad agropecuaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(171, 'contabilidad agricola ganadera', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(172, 'contabilidad de cooperativas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(173, 'contribuyentes designados por la rg 9021', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(174, 'conversatorio nrc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(175, 'curso de excel para contadores', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(176, 'decisiones estrategica de las asambleas del 2021', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(177, 'derecho y gobierno societario', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(178, 'diplomado prevencion de lavado de activos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(179, 'due diligence societario', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(180, 'ejercicio practico de confeccion de de matriz de riesgos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(181, 'elaboracion de manuales de cumplimiento alacftfp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(182, 'gabinete de ejercicios practicos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(183, 'gabinete de retenciones', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(184, 'gobierno societario rgano de administracion rgano de decisionrgano de control stakeholers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(185, 'idu e ire desde cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(186, 'imposicion a los dividendos y utilidades idu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(187, 'impuesto a  la renta empresarial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(188, 'impuesto al valor agregado iva', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(189, 'impuesto selectivo al consumo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(190, 'impuestos al valor agregado iva', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(191, 'interpretacion eeff y cierre fiscal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(192, 'liquidacion del ire', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(193, 'manejo de sociedades desde cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(194, 'maraton de retenciones', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(195, 'maraton idu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(196, 'mercado de valores negocios fiduciaros y fideicomisos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(197, 'modelo de informe para auditoria externa impositiva', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(198, 'modulo de contabilidad agropecuaria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(199, 'modulo tratamiento tributario de las entidades sin fines de lucro esfl', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(200, 'niif aplicable al cierre fiscal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(201, 'normas internacionales de aseguramiento isae 3000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(202, 'planillas laboorales', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(203, 'primeros auxilios para con el registro electronico rg n 90', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(204, 'redaccion de contratos laborales', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(205, 'regimenes simplicados simple y resimple', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(206, 'registro y actualizacion del beneficiario final', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(207, 'reglas del gafi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(208, 'regulaciones covid', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(209, 'regulaciones emitidas por la seprelad', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(210, 'renta personal irp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(211, 'renta personal irp imposicion a los dividendos idu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(212, 'renta personal irp imposicion a los dividendos idu avanzado', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(213, 'renta personal irp imposicion a los dividendos y utilidades idu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(214, 'resolucion general 29921', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(215, 'responsabilidad civil penal y tributariade los organos de gobierno accionistas sindicoscontadores abogados y representantes de personasjuridicas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(216, 'retenciones del ivaireirp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(217, 'seminario de fiscalidad internacional control de precios de transferencia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(218, 'sociedades desde cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(219, 'taller contable de sociedades', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(220, 'taller de aplicacion practica rg 9021', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(221, 'taller de control de precios de transferencias', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(222, 'taller de disolucion de sociedades', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(223, 'taller de empresas per acciones simplificadas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(224, 'taller de interpretacion eeff y cierre fiscal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(225, 'taller de irp e idu desde cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(226, 'taller de la nueva resolucion 29921 de la seprelad', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(227, 'taller de la rg 9021', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(228, 'taller de los estados financieros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(229, 'taller de manejo de sociedades', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(230, 'taller de renta personal irp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(231, 'taller de resolucion  29921', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(232, 'taller de rg 9021', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(233, 'taller de sociedades', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(234, 'taller eeff y cierre fiscal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(235, 'taller practico sobre planillas laborales', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(236, 'taller rg 49', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(237, 'tratamiento de acciones y obligacionesformales valuacion patrimoniales sa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(238, 'tratamiento tributario de la esfl', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(239, 'tributacion de cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(240, 'tributacion desde cero', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(241, 'valuaciones patrimoniales s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(242, 'COORDINACIÓN NACIONAL EN PLA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(243, 'DE LOS CONTRATOS EN PARTICULAR. PRIMERA PARTE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(244, 'DE LOS CONTRATOS LABORALES Y DE SERVICIOS PERSONALES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(245, 'DEL COMERCIO ELECTRONICO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(246, 'DERECHO PENAL ECONOMICO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(247, 'DISEÑO DE SISTEMA DE INFORMACION GERENCIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(248, 'GOBIERNO SOCIETARIO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(249, 'INTRODUCCION AL DERECHO COMERCIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(250, 'NUEVAS DISPOSICIONES LABORALES SANITARIAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(251, 'PLANIFICACIÓN Y PRÁCTICA DOCENTE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(252, 'PRACTICA PROFESIONAL EN LA LIQUIDACION DE IMPUESTOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(253, 'SOLUCION ALTERNATIVA DE CONFLICTOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(254, 'Impuestos a la Renta de las Personas Físicas', NULL, 'IRP003', '2017', NULL, 40, NULL, NULL, NULL),
	(255, 'Procedimiento Tributario y Defensa del Contribuyente', NULL, 'PTD01', '2022', 84, 40, 2, NULL, NULL),
	(256, 'Auditoría y Fiscalización Tributaria', NULL, 'AFT01', '2022', 13, 40, 2, NULL, NULL),
	(257, 'Tributación al Comercio Exterior', NULL, 'TCE01', '2022', 106, 40, 2.7, NULL, NULL),
	(258, 'Régimen Penal Tributario', NULL, 'RPT001', '2017', NULL, 30, NULL, NULL, NULL),
	(259, 'Normas Internacionales de Auditoría', NULL, 'NIA002', '2017', NULL, 50, NULL, NULL, NULL),
	(260, 'Auditoría Financiera', NULL, 'AFI02', '2022', 7, 40, 2.7, NULL, NULL),
	(261, 'Normas Internacionales de Información Financiera (NIIF)', NULL, 'NIF003', '2017', NULL, NULL, NULL, NULL, NULL),
	(262, 'Auditoría informática', NULL, 'AIN02', '2022', 10, 30, 2.7, NULL, NULL),
	(263, 'Auditoría impositiva', NULL, 'AIM002', '2017', NULL, 40, NULL, NULL, NULL),
	(264, 'Papeles de Trabajo y otras Cuestiones Prácticas', NULL, 'PAT01', '2022', 76, 40, 2, NULL, NULL),
	(265, 'Auditoría de Costos ', NULL, 'ACO02', '2022', 5, 40, 2.7, NULL, NULL),
	(266, 'Auditoría Forense y Pericia Contable', NULL, 'AFP01', '2022', 8, 40, 2, NULL, NULL),
	(267, 'Auditoría Interna', NULL, 'AIN02', '2022', 11, 40, 2.7, NULL, NULL),
	(268, 'Auditoría de Gestión', NULL, 'AGE01', '2022', 6, 30, 2, NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
