-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.33 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table test.pais: ~12 rows (approximately)
INSERT INTO `countries` (`name`) VALUES
	('Afganistán'),
	('Albania'),
	('Alemania'),
	('Algeria'),
	('Andorra'),
	('Angola'),
	('Anguila'),
	('Antártida'),
	('Antigua y Barbuda'),
	('Antillas Neerlandesas'),
	('Arabia Saudita'),
	('Argentina'),
	('Armenia'),
	('Aruba'),
	('Australia'),
	('Austria'),
	('Azerbayán'),
	('Bélgica'),
	('Bahamas'),
	('Bahrein'),
	('Bangladesh'),
	('Barbados'),
	('Belice'),
	('Benín'),
	('Bhután'),
	('Bielorrusia'),
	('Birmania'),
	('Bolivia'),
	('Bosnia y Herzegovina'),
	('Botsuana'),
	('Brasil'),
	('Brunéi'),
	('Bulgaria'),
	('Burkina Faso'),
	('Burundi'),
	('Cabo Verde'),
	('Camboya'),
	('Camerún'),
	('Canadá'),
	('Chad'),
	('Chile'),
	('China'),
	('Chipre'),
	('Ciudad del Vaticano'),
	('Colombia'),
	('Comoras'),
	('Congo'),
	('Congo'),
	('Corea del Norte'),
	('Corea del Sur'),
	('Costa de Marfil'),
	('Costa Rica'),
	('Croacia'),
	('Cuba'),
	('Dinamarca'),
	('Dominica'),
	('Ecuador'),
	('Egipto'),
	('El Salvador'),
	('Emiratos Árabes Unidos'),
	('Eritrea'),
	('Eslovaquia'),
	('Eslovenia'),
	('España'),
	('Estados Unidos de América'),
	('Estonia'),
	('Etiopía'),
	('Filipinas'),
	('Finlandia'),
	('Fiyi'),
	('Francia'),
	('Gabón'),
	('Gambia'),
	('Georgia'),
	('Ghana'),
	('Gibraltar'),
	('Granada'),
	('Grecia'),
	('Groenlandia'),
	('Guadalupe'),
	('Guam'),
	('Guatemala'),
	('Guayana Francesa'),
	('Guernsey'),
	('Guinea'),
	('Guinea Ecuatorial'),
	('Guinea-Bissau'),
	('Guyana'),
	('Haití'),
	('Honduras'),
	('Hong kong'),
	('Hungría'),
	('India'),
	('Indonesia'),
	('Irán'),
	('Irak'),
	('Irlanda'),
	('Isla Bouvet'),
	('Isla de Man'),
	('Isla de Navidad'),
	('Isla Norfolk'),
	('Islandia'),
	('Islas Bermudas'),
	('Islas Caimán'),
	('Islas Cocos (Keeling)'),
	('Islas Cook'),
	('Islas de Åland'),
	('Islas Feroe'),
	('Islas Georgias del Sur y Sandwich del Sur'),
	('Islas Heard y McDonald'),
	('Islas Maldivas'),
	('Islas Malvinas'),
	('Islas Marianas del Norte'),
	('Islas Marshall'),
	('Islas Pitcairn'),
	('Islas Salomón'),
	('Islas Turcas y Caicos'),
	('Islas Ultramarinas Menores de Estados Unidos'),
	('Islas Vírgenes Británicas'),
	('Islas Vírgenes de los Estados Unidos'),
	('Israel'),
	('Italia'),
	('Jamaica'),
	('Japón'),
	('Jersey'),
	('Jordania'),
	('Kazajistán'),
	('Kenia'),
	('Kirgizstán'),
	('Kiribati'),
	('Kuwait'),
	('Líbano'),
	('Laos'),
	('Lesoto'),
	('Letonia'),
	('Liberia'),
	('Libia'),
	('Liechtenstein'),
	('Lituania'),
	('Luxemburgo'),
	('México'),
	('Mónaco'),
	('Macao'),
	('Macedônia'),
	('Madagascar'),
	('Malasia'),
	('Malawi'),
	('Mali'),
	('Malta'),
	('Marruecos'),
	('Martinica'),
	('Mauricio'),
	('Mauritania'),
	('Mayotte'),
	('Micronesia'),
	('Moldavia'),
	('Mongolia'),
	('Montenegro'),
	('Montserrat'),
	('Mozambique'),
	('Namibia'),
	('Nauru'),
	('Nepal'),
	('Nicaragua'),
	('Niger'),
	('Nigeria'),
	('Niue'),
	('Noruega'),
	('Nueva Caledonia'),
	('Nueva Zelanda'),
	('Omán'),
	('Países Bajos'),
	('Pakistán'),
	('Palau'),
	('Perú'),
	('Panamá'),
	('Papúa Nueva Guinea'),
	('Paraguay'),
	('Palestina'),
	('Polinesia Francesa'),
	('Polonia'),
	('Portugal'),
	('Puerto Rico'),
	('Qatar'),
	('Reino Unido'),
	('República Centroafricana'),
	('República Checa'),
	('República Dominicana'),
	('Reunión'),
	('Ruanda'),
	('Rumanía'),
	('Rusia'),
	('Sahara Occidental'),
	('Samoa'),
	('Samoa Americana'),
	('San Bartolomé'),
	('San Cristóbal y Nieves'),
	('San Marino'),
	('San Martín (Francia)'),
	('San Pedro y Miquelón'),
	('San Vicente y las Granadinas'),
	('Santa Elena'),
	('Santa Lucía'),
	('Santo Tomé y Príncipe'),
	('Senegal'),
	('Serbia'),
	('Seychelles'),
	('Sierra Leona'),
	('Singapur'),
	('Siria'),
	('Somalia'),
	('Sri lanka'),
	('Sudáfrica'),
	('Sudán'),
	('Suecia'),
	('Suiza'),
	('Surinám'),
	('Svalbard y Jan Mayen'),
	('Swazilandia'),
	('Tadjikistán'),
	('Tailandia'),
	('Taiwán'),
	('Tanzania'),
	('Territorio Británico del Océano Índico'),
	('Territorios Australes y Antárticas Franceses'),
	('Timor Oriental'),
	('Togo'),
	('Tokelau'),
	('Tonga'),
	('Trinidad y Tobago'),
	('Tunez'),
	('Turkmenistán'),
	('Turquía'),
	('Tuvalu'),
	('Ucrania'),
	('Uganda'),
	('Uruguay'),
	('Uzbekistán'),
	('Vanuatu'),
	('Venezuela'),
	('Vietnam'),
	('Wallis y Futuna'),
	('Yemen'),
	('Yibuti'),
	('Zambia'),
	('Zimbabue');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
